#!/bin/sh
# Date and Time Shell CGI script

echo "Content-Type: text/html"
echo ""

CURRENT_DATE=$(date +"%Y-%m-%d")
CURRENT_TIME=$(date +"%H:%M:%S")
FULL_DATE=$(date +"%A, %B %d, %Y")
TIMESTAMP=$(date +%s)
TIMEZONE=$(date +%Z)
WEEK=$(date +%V)
DAY_OF_YEAR=$(date +%j)

cat << EOF
<!DOCTYPE html>
<html>
<head>
    <title>Date & Time - Shell CGI</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, #1b5e20 0%, #388e3c 50%, #1b5e20 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
            color: #fff;
        }
        .container {
            text-align: center;
            padding: 40px;
        }
        h1 {
            margin-bottom: 30px;
            font-weight: 300;
        }
        .time-display {
            font-size: 5em;
            font-weight: 200;
            font-family: 'Monaco', 'Consolas', monospace;
            margin: 20px 0;
            text-shadow: 0 0 30px rgba(174,213,129,0.5);
        }
        .date-display {
            font-size: 1.4em;
            color: rgba(255,255,255,0.8);
            margin-bottom: 40px;
        }
        .info-grid {
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            gap: 15px;
            max-width: 400px;
            margin: 0 auto;
        }
        .info-item {
            background: rgba(255,255,255,0.1);
            padding: 15px;
            border-radius: 10px;
        }
        .info-label {
            color: rgba(255,255,255,0.6);
            font-size: 0.85em;
            margin-bottom: 5px;
        }
        .info-value {
            color: #aed581;
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 1.2em;
        }
        a {
            color: #aed581;
            text-decoration: none;
            display: inline-block;
            margin-top: 30px;
        }
        a:hover { text-decoration: underline; }
        .shell-badge {
            background: rgba(0,0,0,0.3);
            padding: 5px 15px;
            border-radius: 20px;
            font-size: 0.8em;
            color: #aed581;
            display: inline-block;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📅 Date & Time</h1>
        
        <div class="time-display">$CURRENT_TIME</div>
        <div class="date-display">$FULL_DATE</div>
        
        <div class="info-grid">
            <div class="info-item">
                <div class="info-label">ISO Date</div>
                <div class="info-value">$CURRENT_DATE</div>
            </div>
            <div class="info-item">
                <div class="info-label">Timestamp</div>
                <div class="info-value">$TIMESTAMP</div>
            </div>
            <div class="info-item">
                <div class="info-label">Timezone</div>
                <div class="info-value">$TIMEZONE</div>
            </div>
            <div class="info-item">
                <div class="info-label">Week #</div>
                <div class="info-value">$WEEK</div>
            </div>
            <div class="info-item">
                <div class="info-label">Day of Year</div>
                <div class="info-value">$DAY_OF_YEAR</div>
            </div>
            <div class="info-item">
                <div class="info-label">Generated By</div>
                <div class="info-value">Shell</div>
            </div>
        </div>
        
        <div class="shell-badge">🐚 Generated by /bin/sh</div>
        
        <br>
        <a href="/"><- Back to Test Suite</a>
    </div>
</body>
</html>
EOF
