#!/usr/bin/env python3
# Simple Hello World CGI script

import sys

# CGI header - MUST be followed by blank line
sys.stdout.write("Content-Type: text/html\r\n")
sys.stdout.write("\r\n")

# HTML body
sys.stdout.write("""<!DOCTYPE html>
<html>
<head>
    <title>Hello from Python CGI</title>
    <style>
        body {
            font-family: sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
        }
        .container {
            background: white;
            padding: 40px 60px;
            border-radius: 15px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
            text-align: center;
        }
        h1 { color: #667eea; }
        a { color: #667eea; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hello from Python CGI!</h1>
        <p>This page was generated by a Python CGI script.</p>
        <br>
        <a href="/">Back to Test Suite</a>
    </div>
</body>
</html>
""")
sys.stdout.flush()

