#!/bin/sh
# Simple Hello World Shell CGI script

# CGI header with CRLF line endings
printf "Content-Type: text/html\r\n"
printf "\r\n"

# HTML body
cat << 'ENDHTML'
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <title>Hello from Shell CGI</title>
    <style>
        body {
            font-family: sans-serif;
            background: linear-gradient(135deg, #1b5e20 0%, #4caf50 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            margin: 0;
        }
        .container {
            background: white;
            padding: 40px 60px;
            border-radius: 15px;
            text-align: center;
        }
        h1 { color: #2e7d32; }
        a { color: #2e7d32; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Hello from Shell CGI!</h1>
        <p>This page was generated by a Shell script.</p>
        <br>
        <a href="/">Back to Test Suite</a>
    </div>
</body>
</html>
ENDHTML
